server.port=8081
spring.application.name=rest-server


# PostgreSQL Database Configuration
postgres.host=
postgres.port=5432
postgres.database=postgres
postgres.username=
postgres.password=
postgres.sql=